### ISSUE TITLE
This is a request to add .spam back

### ISSUE THREAD

**Issue by Zelqx** [horionclient/Horion#105]
.spam was way easier and simpler, without having to edit the message and turning it on, on the gui. and its faster than the current one. if its possible can we have .spam '(Count) (message)' back?

**Comment by Zelqx** [comment]
I also have people agreeing with me

**Comment by Greloom-Yeet** [comment]
I agree

**Comment by Armagann** [comment]
+1

**Comment by Armagann** [comment]
`.spam <count> <delayInMs> <message>`

`.spam 30 50 Hello World`

**Comment by Armagann** [comment]
`.spam <count> <delayInMs> <message>`

`.spam 30 50 Hello World`

*Send the same message 30 times with 50 millisecond delay*

[Click here to vote](https://github.com/horionclient/Horion/issues/105 'just vote it!')

**Comment by Vonr** [comment]
i dont think delay in ms is possible, ticks yes
