### ISSUE TITLE
When ESP is active and a mob is named it shows up as a player

### ISSUE THREAD

**Issue by TheGoatGuy** [horionclient/Horion#110]
![Minecraft](https://user-images.githubusercontent.com/56893464/67324200-56219e80-f50b-11e9-9a12-6a615e19dc2a.png)
The ESP shows up for a player instead of a mod when you name it with a name tag

**Comment by SurvirvorHRG** [comment]
okay i'm gonna work on it

**Comment by Zelqx** [comment]
Damn, I add a post about this last time. 
It’s been patched now anyways, please close this post 👍

**Comment by Zelqx** [comment]
Please close this my dude :D
