### ISSUE TITLE
Cant download dll

### ISSUE THREAD

**Issue by bobery159** [horionclient/Horion#111]
horion is not injecting for me so i tried to update it by downloading the v2.0 dll update.
cant download file and cannot use horion. plz help

**Comment by richardletshacks** [comment]
The injection isn't working? Does it just say "Success" and that's it?
If so, please download install Visual C++ redistributables[ (Click here to download)](https://aka.ms/vs/16/release/vc_redist.x64.exe)

**Comment by bobery159** [comment]
i have tried installing vc++ 2015-2019 already. going to compile it as described in the installation guide.

didnt have this issue before today. just suddenly stopped working
