### ISSUE TITLE
Bhop settings are stupid

### ISSUE THREAD

**Issue by AlphaTheDeveloper** [horionclient/Horion#114]
I liked the old bhop better because the new one is just wacky - It's a great idea that you can set your speed, but your jump height, not-so much. I try to make my settings much like the old one, to no availl. I like the new bhop, but I find that **adding jump height settings are stupid.**

**Comment by Zelqx** [comment]
i think its a great idea, if you dont like it set your speed to max and height to 34, better than the last bhop. not sure if you can tell the difference.

**Comment by AlphaTheDeveloper** [comment]
I think it's a great addition too, but i've been experimenting with it, and it looks stupid when i turn it all the way up and jump to the moon whilst going super fast. I know, just tweak the settings but I don't think we would need that much power in the first place. I wish there was just a setting for normal/old bhop.

**Comment by Zelqx** [comment]
They removed the height settings and just left it for height jump to do it

**Comment by Zelqx** [comment]
this post may now be closed
