### ISSUE TITLE
wont work

### ISSUE THREAD

**Issue by waterlemon1667** [horionclient/Horion#117]
ive being using horion for about 2 weeks and when my pc reset it just stopped working ive uninstalled minecraft and reinstalled it and it still doesnt work ive unintalled horion and reinstalled it but still didnt work if you have a solution i would be very thankful

**Comment by waterlemon1667** [comment]
Hi any chance you could sendf me a link to cc+ redistributables so I can downloads it?


Sent from Mail for Windows 10

**Comment by richardletshacks** [comment]
https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by waterlemon1667** [comment]
Thank you very much it works now

Sent from Mail for Windows 10

**Comment by richardletshacks** [comment]
Np
