### ISSUE TITLE
Xray removes all shading, doesn't let you see through blocks

### ISSUE THREAD

**Issue by shortbow123** [horionclient/Horion#127]
When Xray is activated it removes the shading, no blocks I have seen are removed from the players view. 
![Capture](https://user-images.githubusercontent.com/18692545/68078244-61888b80-fd8f-11e9-89f3-f34a417a6be5.PNG)

**Comment by shortbow123** [comment]
I have looked around and I have noticed that entities are not affected by this.

**Comment by Zelqx** [comment]
the no shading for the Xray is normal, just makes it look cleaner when looking at ore through blocks. But the xray is indeed broken in 1.13 minecraft

**Comment by Zelqx** [comment]
Please close this as it’s already been patched

**Comment by Damakermiddle** [comment]
^
