### ISSUE TITLE
Font Feature

### ISSUE THREAD

**Issue by Zelqx** [horionclient/Horion#129]
Add a option to were we could select the old font used in 1.12.1 horion.

**Comment by Damakermiddle** [comment]
ok ez ill do it

**Comment by Damakermiddle** [comment]
just gimme what font I forgot XD

**Comment by CSSFx13** [comment]
Noto sans

**Comment by Zelqx** [comment]
Noto sans @Damakermiddle

**Comment by Damakermiddle** [comment]
kkk

**Comment by Damakermiddle** [comment]
Ight, so I ran into a problem.  If you want the norm font, you need to get a diff dll, you cant make it as a toggle as ITS FUCKING STATIC >_<

**Comment by Damakermiddle** [comment]
I yeeted the gamer font out here take this

[Horion.zip](https://github.com/horionclient/Horion/files/3806362/Horion.zip)

**Comment by Zelqx** [comment]
thanks

**Comment by Zelqx** [comment]
@Damakermiddle Can you add me on discord and tell me how to switch the fonts? Zelqx#0001

**Comment by Zelqx** [comment]
Old fonts been added back
