### ISSUE TITLE
Noclip Request

### ISSUE THREAD

**Issue by Zelqx** [horionclient/Horion#131]
Request to add noclip, can go up Y coord and Z and X without any trouble. And to phase through blocks while using it.

**Comment by k1ngboo** [comment]
Fly + Phase?????????

**Comment by ASOwnerYT** [comment]
'Phase' and 'Fly' modules already exist.

**Comment by Zelqx** [comment]
Phase won’t let you go up and down. Please don’t be stupid lmao

**Comment by k1ngboo** [comment]
> Phase won’t let you go up and down. Please don’t be stupid lmao

I think you are stupid not reading the word fly lol

**Comment by Zelqx** [comment]
@k1ngboo you are fucking stupid, YOU CANT PHASE UP THROUGH BLOCKS. Fucking 13 year old cunt. :smh:
