### ISSUE TITLE
im on 1.13.0 and IT STILL DOESNT WORK AFTER YOU SAID IT WORKS

### ISSUE THREAD

**Issue by joejr08** [horionclient/Horion#132]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Zelqx** [comment]
Close this post and Add me on discord 
Zelqx#0001
(Cap sensitive)

**Comment by Zelqx** [comment]
Most of its features are broken, but the actual cheat it self is working

**Comment by GodGamer029** [comment]
ok
