### ISSUE TITLE
Game crashes on Minecraft 1.13

### ISSUE THREAD

**Issue by solarfluxx** [horionclient/Horion#134]
**Describe the bug**
My game crashes when I try to inject the client. I'm not sure what's causing this to happen. I'm on Minecraft 1.13.0. I've reinstalled the game and this is still happening.

**To Reproduce**
1. Open Horion Injector
2. Click on Inject
3. Game Crashes

**Expected behavior**
I expect the client to be injected without the game crashing.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Horion was working until the new update.

**Comment by Zelqx** [comment]
please close this post and the Developers are fixing this.

**Comment by richardletshacks** [comment]
The latest public release (V2.0.0) does not work on 1.13.
Please use a 1.13 beta build to play on 1.13 with Horion.
