### ISSUE TITLE
Pocket Edition UI

### ISSUE THREAD

**Issue by Choclatesoup** [horionclient/Horion#135]
**Describe the bug**
Whenever I inject the DLL into the game I am automatically switched to the pocket edition UI instead of the classic. I have reinstalled the base game and re-created it multiple times. Once horion is injected I am unable to switch back to classic UI. I have tried some basic troubleshooting in order to see if it is my client, but the issue only occurs when I inject the DLL.

**To Reproduce**
1. Launch Minecraft and go into a world
2. Import the DLL into the client
3. The client will then automatically switch to the Pocket Edition UI and you will no longer be able to switch it back.

**Expected behavior**
To use the game and hack on the normal UI mode.

**Screenshots**
The attached screenshot shows that it appears no UI is selected after I inject the DLL and I am unable to change it at all.
![Capture1](https://user-images.githubusercontent.com/36254276/68095691-3fffd080-fe71-11e9-9a16-2aa600f5f61f.PNG)
![Capture](https://user-images.githubusercontent.com/36254276/68095692-3fffd080-fe71-11e9-9a5e-e46e58a7dbba.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Johnmacrocraft** [comment]
This issue occurs when FullBright is enabled

**Comment by Choclatesoup** [comment]
Thank you.

**Comment by GodGamer029** [comment]
Fixed in 45bd27f
