### ISSUE TITLE
Blink & NoFall

### ISSUE THREAD

**Issue by solarfluxx** [horionclient/Horion#136]
**Describe the bug**
When Blink is on NoFall doesn't work, you still take fall damage.

**To Reproduce**
1. Turn NoFall on
2. Turn Blink on
3. Jump off a cliff
4. You take fall damage and will probably die

**Expected behavior**
I would expect not to take fall damage while NoFall is on.

**Desktop**
 - OS: Windows 10

**Comment by Zelqx** [comment]
Thank you, this has been added to the bug list. Please close this post :D
