### ISSUE TITLE
Crash upon riding Horse

### ISSUE THREAD

**Issue by AquaBarnes** [horionclient/Horion#139]
Once you get on a horse with Horion active you will crash. 

To reproduce the behavior, just ride a horse 

OS: WIN10

Thanks

**Comment by Zelqx** [comment]
Please remove this as it has already been reported on

**Comment by AquaBarnes** [comment]
> 
> 
> Please remove this as it has already been reported on

Sure, but I dont see a report for this issue. Could you give me a link?

**Comment by Zelqx** [comment]
It’s literally in bug lists, now please close this
