### ISSUE TITLE
Fatal Crash and Non responsive relogging

### ISSUE THREAD

**Issue by Polo42069** [horionclient/Horion#147]
**Describe the bug**
Upon taking an item taken from .gm 1 using no packet, disabling no packet, and .dupe ing this item. You will experience a fatal crash. This action will "lock" you out of the realm it was done on, causing a fatal crash after each "World generation: done!" message

**To Reproduce**
1. Go to .gm 1
2. Engage no packet
3. Take item from creative inventory
4. Place item on Hotbar
5. Disengage no packet
6. .dupe the ghost item
7. Fatally crash
8. Be unable to join the realm until a rollback is completed

edit: upon some investigation, it only seems to be a problem with mob heads, doing this with other creative only items such as spawn eggs and potions seems to work fine. .dupe regularly works fine with non  .gm 1 skulls.

**Expected behavior**
Items to either be duped or vanished upon relogging. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Currently using #524338e6 Precompiled dll from #beta-releases

**Comment by Lemons122** [comment]
Just tested, this is not an issue for me :/

**Comment by Lemons122** [comment]
Oh, yeah, it does do a fatal crash when having a skull.

**Comment by Polo42069** [comment]
its only a personal crash though. it seems to work fine for everyone else. and they are none the wiser that you are even having issues

**Comment by richardletshacks** [comment]
Thats a game bug and doesn't have anything to do with Horion, since the game also crashes without Horion being injected.
I assume the data is corrupt and can't be loaded.

Mojang, please fix.

**Comment by Polo42069** [comment]
I would also assume it has something to do with a corrupt item in the offhand. Something that can only be done with a client. At least on bedrock. Just kinda strange it only does it with .gm 1 skulls and not skulls that have been collected by natural means.
