### ISSUE TITLE
Injector dosen't inject Horion

### ISSUE THREAD

**Issue by theschweatyboy** [horionclient/Horion#148]
**Describe the bug**
I open the injector and hit inject. Everything goes as normal and a little thing pops that says "Success" like normal, but there is no in-game evidence that it has injected. The hacks don't work and no GUI appears. 

**To Reproduce**
It happens any time I use the injector.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I have tried downloading the Injector again but that didn't work.

**Comment by richardletshacks** [comment]
If people would just read the message in #read-before-asking.

>Q: Oh no! Injection isn't working, what do I do?
>A: Try installing the C++ Redistributable over at Microsoft's website at https://aka.ms/vs/16/release/vc_redist.x64.exe.

**Comment by Xderar** [comment]
You sure you got all the right version of mc and horion?
