### ISSUE TITLE
.enchant crash

### ISSUE THREAD

**Issue by Quackyyy** [horionclient/Horion#153]
**Describe the bug**
.enchant Crashes you on mineplex

**To Reproduce**
1. Go to 'mineplex'
2. type in .enchant (any enchant)
3. Crash

**Expected behavior**
1. Go to mineplex
2. Type .enchant
3. don't crash lol
**Screenshots**
![image](https://user-images.githubusercontent.com/57575775/68535697-07964180-030c-11ea-99ea-0f861816dcb9.png)
The if causes the crash
**Desktop (please complete the following information):**
 - OS: Windows 1903

**Additional context**
Pretty sure its just the if else statement in the enchant code.

**Comment by Quackyyy** [comment]
The older build works just fine.

**Comment by Johnmacrocraft** [comment]
This issue is already fixed in 7fbfcc181f5665f7b40f77c62bb654b196f16378, you're probably using an outdated build.

**Comment by Quackyyy** [comment]
For mineplex?

**Comment by Quackyyy** [comment]
I used an older build and it worked fine for mineplex, but this newest one crashes if i use .enchant.

**Comment by Johnmacrocraft** [comment]
Yes

**Comment by Quackyyy** [comment]
Alright, I'll try that build and get back to you later
