### ISSUE TITLE
Horion not launching at all anymore

### ISSUE THREAD

**Issue by DarkNight2512** [horionclient/Horion#156]
**Describe the bug**
After the Horion update i didn't got able to inject. even after downgrading Minecraft Bedrock to 1.12.1, it just close 2 seconds after i launch it, and sometimes uninstall itself after some tries

**To Reproduce**
1. Launch Minecraft Win10
2. Open Horion folder 'C:\Users\Download'
3. Launch Horion
2. See error

**Expected behavior**
Horion launching like it always did.

**Screenshots**
None

**Desktop:**
 - OS: Windows 10

**Additional context**
Idk.

**Comment by OhBoyItsGrelAgain** [comment]
Please close the issue. Upgrade to 1.13.0 and compile the beta.

**Comment by k1ngboo** [comment]
Don't waste people's time with your stupidity and pay attention to what's gone on. There are multiple tutorials both written and visual, and if you were in the discord you'd also notice. Close this thread and donate to get beta access at https://patreon.com/horion
