### ISSUE TITLE
Framerate drop when using built 1.13dll

### ISSUE THREAD

**Issue by bigrig112** [horionclient/Horion#159]
Without horion injected using a 1.13 dll from the github repository i get a range of 200-240 fps. Once Horion is injected even with all modules turned off the framrate drops to about 60-100 fps

**Comment by Quackyyy** [comment]
This is because the ESP causes frame drops.

**Comment by bigrig112** [comment]
i turned all modules off and it didnt make a difference esp wasnt on. and when i used the dll for 1.12 when i was on 1.12 it didnt have this big of an impact on my framerate. Even disabling the hud doesnt make a difference

**Comment by Damakermiddle** [comment]
Where u building something when you were playing?? That is literally the only time i get frame drops..

**Comment by Zelqx** [comment]
Probably your pc, if you got a good pc. Most likely you need to allocate for processors

**Comment by bigrig112** [comment]
No I was not building anything  and I even overclocked my cpu and gpu to try to see if it fixed the issue but it did not

**Comment by bigrig112** [comment]
its a very weird issue and so far I’ve tried so many things and I have yet to find a solution. It’s something different between the 1.13 dll and 1.12 and I’m not sure what it is

**Comment by bigrig112** [comment]
Update: the official release for the 1.13 injector doesn’t cause the problem anymore

**Comment by SurvirvorHRG** [comment]
good
