### ISSUE TITLE
Commands not work

### ISSUE THREAD

**Issue by xXArcadeHackXx** [horionclient/Horion#163]
**Commands Not Work**

**To Reproduce**
1. Go to 'a server'
2. Click on 'chat and say .help and this dont say anything.'
3. Scroll down to 'and this not say anything'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/57632095/68623885-ce113200-04d5-11ea-8a3b-9d6da8bd1ff2.png)

**Desktop (please complete the following information):**
 - OS: [WIndows 10 Home]

**Additional context**
Idk.

**Comment by richardletshacks** [comment]
Horion isn't even injected.
Please make sure you have the Visual C++ redistributables installed and then try reinjecting.

**Comment by xXArcadeHackXx** [comment]
i have visual studio c++

**Comment by xXArcadeHackXx** [comment]
all work but the commands doenst work 
look 
![image](https://user-images.githubusercontent.com/57632095/68624544-57753400-04d7-11ea-9a2c-1ff83f8ec42c.png)

**Comment by SurvirvorHRG** [comment]
did you change the prefix ?

**Comment by Zelqx** [comment]
Please close this post :D

**Comment by richardletshacks** [comment]
This is not resolved yet @Zelqx

**Comment by xXArcadeHackXx** [comment]
Yes im changed de prefix

**Comment by richardletshacks** [comment]
No wonder it doesn't work anymore. Use the prefix you set, if you don't remember it anymore delete the config located at `%LocalAppData%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\RoamingState`

**Comment by xXArcadeHackXx** [comment]
omfg thx i love u if i could i kiss you <3

**Comment by Zelqx** [comment]
hmm. thought he didnt have it injected as a comment said on top 🤔
