### ISSUE TITLE
Injector not workin

### ISSUE THREAD

**Issue by chipsandsoda** [horionclient/Horion#164]
**Describe the bug**
Everything is downloaded and used the injector yet nothing is happening

**To Reproduce**
1. Go to Horion Injector 
2. Click on Inject
3.See error 

**Screenshots**
![BB4ADFD4-2D39-4E4B-A8A0-950989AA032C](https://user-images.githubusercontent.com/57643311/68626862-ed8e6780-04a1-11ea-8e25-8182f3c916d9.jpeg)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by louandyDiazYT39** [comment]
my injector is not working i need help, when i press inject nothing happend i have minecraft 1.13.0 tell me how to fix it

**Comment by XITheGrayWolfIX** [comment]
Try installing the lastest horizon Injector?
Go to the main menu and try the inject?

**Comment by Otaiku** [comment]
@XITheGrayWolfIX 

> Try installing the lastest horizon Injector?
* Tried multiple times didn't worked

@louandyDiazYT39 You need to install the latest release of vc_redist.x64.exe! 
https://aka.ms/vs/16/release/vc_redist.x64.exe

Launch your minecraft and horion client. click inject. done.

**Comment by Zelqx** [comment]
Close this post please
