### ISSUE TITLE
Issues with rainbow arraylist~~

### ISSUE THREAD

**Issue by Zamazenta** [horionclient/Horion#165]
"//credit to lemon" Is missing from the code.
Here is why it should be there:
![mxm2ld6](https://user-images.githubusercontent.com/25157685/68628970-22092000-04b0-11ea-9eef-05004413d8b3.png)
thanks guys!

**Comment by SurvirvorHRG** [comment]
what

**Comment by SurvirvorHRG** [comment]
impossible

**Comment by SurvirvorHRG** [comment]
photoshop

**Comment by Zamazenta** [comment]
Its real... You can't fake photos

**Comment by EndmyExistence** [comment]
@Zamazenta its called ctrl shift i and highlight it and change to what you desire

**Comment by SurvirvorHRG** [comment]
@richardletshacks explain yourself

**Comment by richardletshacks** [comment]
still my code and there already are some credits
https://github.com/horionclient/Horion/blob/465ff3f5d56c1e2e2b40b967e50ac046205b6971/Memory/Hooks.cpp#L438

**Comment by Zelqx** [comment]
Close this and leave it on the discord.
