### ISSUE TITLE
Error 06 Bug

### ISSUE THREAD

**Issue by xXArcadeHackXx** [horionclient/Horion#166]
**Error 06**
this error does not allow me to inject.

**To Reproduce**
1. Go to 'Horion'
2. Click on 'Inject'

**Screenshots**
![image](https://user-images.githubusercontent.com/57632095/68692835-78d92d00-0576-11ea-9a03-0f153670d8ec.png)
**Desktop (please complete the following information):**
 - OS: [WIndows 10 Home]

**Additional context**
I have everything I need installed and it gives me that error.

**Comment by xXArcadeHackXx** [comment]
pls help me

**Comment by GodGamer029** [comment]
This repository is for the actual client and not the injector. Your problem is probably caused by your antivirus

**Comment by xXArcadeHackXx** [comment]
i dont have antivirus in my pc this is for noobs xd (ok rly i don haver a antivirus)

**Comment by BadComputer6969** [comment]
i can't inject either but don't get an error just nothing happens although it says on interface success and done
