### ISSUE TITLE
Just won't work

### ISSUE THREAD

**Issue by AlxPlays** [horionclient/Horion#167]
Whenever i click 'inject' it will say 'Success' and nothing will appear on minecraft

what i did was
1. Opened 'horioninjector.exe'
2. Clicked on inject
3. Success came up
4. Nothing happens

 - OS: Windows 10

I have also Disabled my antivirus

**Comment by BadComputer6969** [comment]
Same m8 happened to me too

**Comment by BadComputer6969** [comment]
i uninstalled the windows one aswell
