### ISSUE TITLE
The gui on the injector says done

### ISSUE THREAD

**Issue by BadComputer6969** [horionclient/Horion#168]
**Describe the bug**
The injector show that it is working yet when i enter a game there is no hud and nothing appears to be functional.
**To Reproduce**
1. Go to 'injector'
2. Click on 'inject'
3. Wait till the injector says "done"
4. See nothing has happened

**Expected behavior**
"nothing" 
**Screenshots**
![image](https://user-images.githubusercontent.com/57681680/68697740-5f84b080-0577-11ea-9642-65f73a8c6ba6.png)
![image](https://user-images.githubusercontent.com/57681680/68697774-6ca19f80-0577-11ea-8008-2bc7404d4514.png)

**Desktop (please complete the following information):**
Windows 10 Home (obviously)

**Comment by BadComputer6969** [comment]
ive tried closing and reopening it multiple times

**Comment by GodGamer029** [comment]
Wait for the new injector
