### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by richardletshacks** [horionclient/Horion#170]
Let Horion display some nice Rich Presence information (toggleable)
Todo:
- [ ] Setup Discord Game SDK
- [ ] Setup some kind of Manager managing the discord SDK
- [ ] If manager was able to connect to the discord instance, push DiscordRPC module
- [ ] If module is enabled, update RPC status every 5-10 seconds with some information like server currently playing on and module count (enabled out of max module count)

**Comment by k1ngboo** [comment]
You would need to create a group, and pay for the license in the developer portal.

**Comment by richardletshacks** [comment]
> You would need to create a group, and pay for the license in the developer portal.

No, the sdk is free. As long as ur not uploading some game, you can create bots and applications using the sdk/api for free. Teams are free too.

**Comment by Zelqx** [comment]
@k1ngboo rekt
