### ISSUE TITLE
Hack isn’t working 

### ISSUE THREAD

**Issue by chipsandsoda** [horionclient/Horion#171]
**Describe the bug**
Hack won’t work when download is complete
**To Reproduce**
1. Go to Horion injector 
2. Click on Inject
3.See error

**Expected behavior**
The Horion sign to show up in the bottom right corn of Minecraft 

**Screenshots*
![1725A082-E0F3-4848-A778-6D8995D3A036](https://user-images.githubusercontent.com/57643311/68717045-47a72f80-056b-11ea-8968-1086bc585414.jpeg)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Had this problem and someone told me that it doesn’t work with x86 C++ but deleted it and downloaded x64 and didn’t change a single thing. Also have tried deleting the injector and re downloading it but that didn’t change anything

**Comment by Zelqx** [comment]
what is the error?

**Comment by chipsandsoda** [comment]
When I click inject the hack will not even work and the key I use to toggle the menu won’t work either

**Comment by Waylon802** [comment]
Yeah same with me to.

**Comment by pyrozone889** [comment]
I have the same problem. It will not work when i press insert and does not say horion in bottom right corner.

**Comment by dillydirkes** [comment]
Same problem, i thought it was because i had 1.13.1 but nope. its happening to 1.13.0 too kinda strange im sure they will fix it soon

**Comment by Zelqx** [comment]
We are not having any problems, you probably need to disable your Anti virus or open the cheat with administrator permission

**Comment by xXArcadeHackXx** [comment]
it still doesn't work

**Comment by xXArcadeHackXx** [comment]
And if I restart my factory computer I delete everything will work?

**Comment by xXArcadeHackXx** [comment]
ok this is a error i use extreme injector and this work donwload extreme injector horion ijector not work : ) 
![image](https://user-images.githubusercontent.com/57632095/68762390-5f87bd80-0616-11ea-9504-4ea1065adca0.png)

**Comment by richardletshacks** [comment]
Do you have the files `vcruntime140.dll` and `vcruntime140_1.dll` in your System32 folder, if it doesn't inject for you?

**Comment by xXArcadeHackXx** [comment]
this?
![image](https://user-images.githubusercontent.com/57632095/68763364-8a731100-0618-11ea-8e24-80f9e0404e8f.png)

**Comment by richardletshacks** [comment]
> this? i have 5
> ![image](https://user-images.githubusercontent.com/57632095/68763364-8a731100-0618-11ea-8e24-80f9e0404e8f.png)

Yes. If you have these two files, Visual C++ redistributables in general, and it still doesn't inject, try another injector. If this works, please check if Horion Injector is blocked by your AntiVirus.

**Comment by xXArcadeHackXx** [comment]
yes i use other injector :D

**Comment by reed77** [comment]
what injector did u use?
i cant get it to work

**Comment by MysteryTaylor** [comment]
They are using Extreme injector, but i tried and i keep getting this error.
![image](https://user-images.githubusercontent.com/57728752/68799599-59163780-0650-11ea-852d-199335f34680.png)

**Comment by RG0DAL** [comment]
how do we check if anti-virus is blocking it?

**Comment by MysteryTaylor** [comment]
Well it prob pops up in your face like avast

**Comment by RG0DAL** [comment]
I dont have avast and nothing pops up

**Comment by MysteryTaylor** [comment]
hmmm. well from what i have been trying i have no way of doing this, if they can fix the horion injector this could be solved in a flash.

**Comment by RG0DAL** [comment]
yea

**Comment by MysteryTaylor** [comment]
or if i knew what this ment i could try to find a way 
![image](https://user-images.githubusercontent.com/57728752/68800089-51a35e00-0651-11ea-93ce-b50e2482c731.png)

**Comment by RG0DAL** [comment]
I just downloaded extreme injector v3, but it won't even open

**Comment by Zelqx** [comment]
Stop talking here!!!!!! talk about it in the discord in #horion_textable. Only message if you can help.

**Comment by MysteryTaylor** [comment]
https://wearedevs.net/d/Extreme%20Injector i'm just putting this here cuz my phone is ded so i can't verify it yet
