### ISSUE TITLE
Hack Isnt Working

### ISSUE THREAD

**Issue by Eternity101** [horionclient/Horion#172]
When I inject the dll i get "success" but nothing actually happens or changes in minecraft.
I have ran it as administer, used other dll injectors, but it doesnt work with 1.13

![PrtScr capture_5](https://user-images.githubusercontent.com/57734274/68814858-dbe6c480-0647-11ea-9269-c0538d824117.jpg)

**Comment by richardletshacks** [comment]
**Please don't open a new issue each time, take a look at existing issues first!**
Do you have the Visual C++ redistributables installed?

**Comment by Eternity101** [comment]
Yep i do

**Comment by Eternity101** [comment]
It used to work before but now it does not when 1.13 came out
