### ISSUE TITLE
Doesn´t work

### ISSUE THREAD

**Issue by OfflinePing** [horionclient/Horion#176]
Hi,
I tried to use the hack, but nothing happened. I use the Minecraft windows 10 version 1.13.1. I also installed Microsoft Virsual C ++ 2015. There is also the message success but nothing happens. 

![WICHTIG](https://user-images.githubusercontent.com/54213976/68964094-c81e9800-07d8-11ea-89af-a9e496532f2c.png)

LG,
OfflinePing

**Comment by chipsandsoda** [comment]
Same issue have everything installed an even uninstalled and reinstalled it but isn’t working

**Comment by CoolStuff08** [comment]
You need VISUAL STUDIO 2019 REDISTRIBUTABLES or the 2015-2019 redistributables. Not just 2015.
