### ISSUE TITLE
Injection doesnt work

### ISSUE THREAD

**Issue by 2cool4u567** [horionclient/Horion#178]
The Injection still doesnt work, ive been trying every single month since it came out, i install new injection and the new .dll try it and it still doesnt work. Please fix it.

**Comment by Damakermiddle** [comment]
#ReadBeforeAsking:

Horion Frequently Asked Questions:

Q: Help! I don't have access to all channels! Where do I chat?
A: You need to accept the rules first. React with that tiny :accept: in #important 

Q: How do I download the beta builds?
A: Beta builds are for Patrons and Nitro Boosters only, if you are one, go to #beta-releases 

Q: Oh no! I closed my TabGUI! What do I do?
A: TabGUI is now merged into one module called HUD. To toggle HUD, type .toggle hud in the chat of any game!

Q: How do I obtain items from .gamemode 1?
A: See the tutorial over at https://streamable.com/fnez0

Q: Oh no! Injection isn't working, what do I do?
A: Try installing the C++ Redistributable over at Microsoft's website at https://aka.ms/vs/16/release/vc_redist.x64.exe.

Q: How do I suggest new features or contribute to the project?
A: To suggest new features, you can execute the .suggest command in #commands! To contribute to the project, simply go to the project's GitHub page, make a fork, edit what you want and make a pull request!

___________________________________________________________________________________________________________
Its in the discord brainlet

**Comment by Damakermiddle** [comment]
close this or your gay

**Comment by 2cool4u567** [comment]
I have already read all of that along time ago.. and also it's not nice to assume peoples sexuality. Personally I am Heterosexual so your statement "close this or your gay" make no sense.

**Comment by sdadasdasdasdwasdw** [comment]
> I have already read all of that along time ago.. and also it's not nice to assume peoples sexuality. Personally I am Heterosexual so your statement "close this or your gay" make no sense.

Can you shut up and close the thread
