### ISSUE TITLE
Commands do not work

### ISSUE THREAD

**Issue by MKF-tech** [horionclient/Horion#179]
Every time they enter the command it displays in chat it doesn't excuse the command
![15740079463495268780927213346655](https://user-images.githubusercontent.com/54194095/69010364-f4f8b980-0956-11ea-8723-19de204d7cd3.jpg)

**Comment by GodGamer029** [comment]
Minecraft version?

**Comment by MKF-tech** [comment]
1.13.1

**Comment by xXArcadeHackXx** [comment]
u changed the prefix?

**Comment by MKF-tech** [comment]
yea

**Comment by xXArcadeHackXx** [comment]
ok delete this archive press windows+r and paste this %LocalAppData%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\RoamingState

**Comment by MKF-tech** [comment]
Ok I delete the folder

**Comment by xXArcadeHackXx** [comment]
now inject and say .help

**Comment by xXArcadeHackXx** [comment]
first close all (injector & minecraft)

**Comment by MKF-tech** [comment]
ok

**Comment by MKF-tech** [comment]
ok it worked

**Comment by xXArcadeHackXx** [comment]
do not do it again
