### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by FuseGM** [horionclient/Horion#180]
I downloaded the Windows Visual C++ and the new Horion Injector and when i press inject it says "Successful" but the thing does not pop up. I went into a game a did the .open TabGui and stuff but still does not work. It worked before the 1.13 update but not no more. How someone could tell me how to fix this.

**Comment by FuseGM** [comment]
I also have tried .toggle hud but all it does is type the actual thing in chat

**Comment by RealEnzoTDZ** [comment]
mine crashes when it says done
