### ISSUE TITLE
This is a deal breaker for me.

### ISSUE THREAD

**Issue by NYPDK** [horionclient/Horion#191]
https://ibb.co/grR3ZCd

I refuse to use this sketchy and poorly made injector. I will no longer be using this cheat, sayonara!

**Comment by GodGamer029** [comment]
Thank you for your helpful feedback then?

**Comment by S-B99** [comment]
Honestly everyone shitting on the injector and saying they won't use it are children.

Like, don't create an issue for the sole purpose of complaining, give feedback at the very least.

**Comment by NYPDK** [comment]
Look, if you want helpful feedback. Then my suggestion is to at least let people use their own injector, yours is fine but I genuinely don't like having to use this injector for multiple reasons. 

Also sorry for being such a bitch the other day, it wasn't a good day for me and I was venting to a fucking GitHub project.

**Comment by GodGamer029** [comment]
What about stating those reasons?

**Comment by DylanVidzOnYT** [comment]
weeee
