### ISSUE TITLE
Injection

### ISSUE THREAD

**Issue by furrytrash69** [horionclient/Horion#192]
I've turned off all AntiVirus on my computer. Yet, I can't seem to get the injector to work. Everytime I look at the Horion Injector tab it says "An error occurred", " probably due to your Antivirus" The word probably leaves me a tad confused. What else could be causing the injector not to work?

**Comment by DylanVidzOnYT** [comment]
try removing it from quontibed list 


and say to Ur antivirus it's not a virus u idot

**Comment by DylanVidzOnYT** [comment]
also if that doesn't work try renstaling it after this done ^^^

**Comment by OhBoyItsGrelAgain** [comment]
can you genuinely shut the fuck up? you contribute nothing to these issues

**Comment by DylanVidzOnYT** [comment]
you didn't help then

**Comment by furrytrash69** [comment]
> try removing it from quontibed list
> and say to Ur antivirus it's not a virus u idot

I'm sorry, what's a quontibed list? Not sure if it's a typo or not.

**Comment by DylanVidzOnYT** [comment]
tei poo
