### ISSUE TITLE
Horion not recognizing dll with multiple accounts on one pc 

### ISSUE THREAD

**Issue by Temmiekat** [horionclient/Horion#193]
when trying horion on a second account on my pc it wont recognize the dll so you have to download it from the github and go to your main drive then to users then double click the current user go to downloads and the dll should be there.

**Comment by richardletshacks** [comment]
What do you mean by "recognize the dll"?
You just need to click inject, thats it. No need for downloading the dll yourself

**Comment by DylanVidzOnYT** [comment]
ahahhaahh
