### ISSUE TITLE
AntiVirus 

### ISSUE THREAD

**Issue by zummerHere** [horionclient/Horion#194]
"An Error occured. The DLL was not Loaded. This is probably due to your AntiVirus. "    What to do? Antivirus disabled

**Comment by S-B99** [comment]
Uninstall windows, it's probably detecting that as a virus

**Comment by zummerHere** [comment]
> Uninstall windows, it's probably detecting that as a virus

I don't speak English
I have disabled antivirus Windows, but still does not start

**Comment by DylanVidzOnYT** [comment]
??????????

**Comment by DylanVidzOnYT** [comment]
> ??????????

ooooh you can quote

**Comment by zummerHere** [comment]
> > ??????????
> 
> ooooh you can quote

what's the quote?
