### ISSUE TITLE
Fix Valea

### ISSUE THREAD

**Issue by BalisticMC** [horionclient/Horion#195]
Hello when i join to valea and inject its eject instandly 

please fix

**Comment by BalisticMC** [comment]
Im sorry my english is not the best xD

**Comment by OhBoyItsGrelAgain** [comment]
Sex Moment Gaming.
You need to compile Horion and remove the check that uninjects if it detects you're on Valea.

**Comment by Vonr** [comment]
its in Loader.cpp
