### ISSUE TITLE
HUD causes crash in servers

### ISSUE THREAD

**Issue by enajor66** [horionclient/Horion#199]
The bug occurs whenever I try to play the game with the HUD enabled.
1. Go to a server
2. launch into the game
3. Turn the HUD on
**Expected behavior**
HUD to turn on and work like normal

- OS: Windows 10 Pro
-GPU: Nvidia quadro k4100m
-CPU: i7 4810mq
-RAM: 8gb DDR3

**Comment by S-B99** [comment]
try uninstalling windows that should fix the issue

**Comment by SylveonBottle** [comment]
> try uninstalling windows that should fix the issue

was having same issued, tried doing recommended fix and now my computer won't boot. don't recommend

pls fix
