### ISSUE TITLE
Add TP-Aura

### ISSUE THREAD

**Issue by ghost** [horionclient/Horion#2]

**Comment by BrandonioR** [comment]
Any server with an anti cheat can get past this, good for hvh realms i suppose tho

**Comment by thisisafakeacount** [comment]
what is sad is that flare client has this

**Comment by supercoolgamer35** [comment]
> what is sad is that flare client has this

What is sad is your bumping a 4 month old thread. Why don't I count for you the endless amount of features horion has over flare?

**Comment by DisabledMallis** [comment]
hey guys

**Comment by supercoolgamer35** [comment]
> hey guys

Hi qt

**Comment by GreenPlumTea** [comment]
@GodGamer029 

If this is done, don't forget to close it lmao
