### ISSUE TITLE
Add a Client Chat

### ISSUE THREAD

**Issue by ghost** [horionclient/Horion#20]
- [ ] Somehow connect to an IRC
- [ ] Somehow say something

**Comment by BrandonioR** [comment]
This is already a thing on existing java clients and could be implemented although we'll need a host

**Comment by richardletshacks** [comment]
Add this and then sync it to discord

**Comment by BrandonioR** [comment]
> Add this and then sync it to discord

webhook maybe?

**Comment by DylanVidzOnYT** [comment]
that's a good idea

**Comment by thisisafakeacount** [comment]
you could probably just have a font that changes the letters but on the receiving end will translate it back and it cold be togglable

**Comment by GrelTheL** [comment]
dont necropost
