### ISSUE TITLE
Scaffold Silent Mode

### ISSUE THREAD

**Issue by ghost** [horionclient/Horion#21]
You shouldnt have to switch to the block to build
steps:
- [x] Find Hotbar Items
- [ ] Select Hotbar Item

**Comment by akmvihfan** [comment]
ya important

**Comment by Damakermiddle** [comment]
how do u kno when to switch tho

**Comment by richardletshacks** [comment]
That's not a problem, it works, but actually doesn't
We would have to add delay, but this has low priority

**Comment by Meliodas541** [comment]
I agree with this, we need a better scaffold. It seems like they tried to add a silent scaffold but it glitches.
