### ISSUE TITLE
Updateeeee

### ISSUE THREAD

**Issue by MysticD3AD** [horionclient/Horion#212]
**Describe the bug**
The HorionClient not working as intended.

**To Reproduce**
1. Inject Horion
2. Try to use a hack
3. It doesn't work, infact; none of them work.

**Expected behavior**
The HorionClient to work / be updated

**Screenshots**
https://gyazo.com/55d73a7c21a182022ecde7d8e4afd022

**Desktop (please complete the following information):**
 - OS: Windows 10  |  Version 1903  |  Build 18362.535

**Additional context**
none

**Comment by SylveonBottle** [comment]
Potentially due to the 1.14 update, but I am having the same issue.
Main menu completely stops working (buttons highlight but can't click), etc.
