### ISSUE TITLE
Horion Discord is gone

### ISSUE THREAD

**Issue by GodGamer029** [horionclient/Horion#214]
keep relevant discussion here and don't open new issues

**Comment by thkdlflghlsdghilr** [comment]
This is relevant

**Comment by brandonr1337** [comment]
Do you have a telegram? Or is your discord account not banned

**Comment by Zelqx** [comment]
Make a new account and new discord for temp

**Comment by Olybear9** [comment]
Retards really out here reporting horion -_-

**Comment by Zelqx** [comment]
ikr

**Comment by MoistSushi** [comment]
Smh people are just butthurt🤦🏽‍♂️

**Comment by GodGamer029** [comment]
New Discord: https://discordapp.com/invite/Xkz6VWR
