### ISSUE TITLE
HORION REFUGEE DISCORD 

### ISSUE THREAD

**Issue by Zelqx** [horionclient/Horion#215]
https://discord.gg/e3JdkPn - This is until the main discord comes back/becomes recreated

**Comment by brandonr1337** [comment]
note for those joining - this isnt by the devs, its managed by me and zelqx (just contributors) and once a new horion discord is up it will be posted there and the server will be deleted after everyone has joined the official new one

**Comment by GodGamer029** [comment]
#214
