### ISSUE TITLE
Injector

### ISSUE THREAD

**Issue by dudeisbrendan03** [horionclient/Horion#226]
![image](https://user-images.githubusercontent.com/6009600/71561900-dbc64b00-2a74-11ea-9f4e-2cbc39204a48.png)
![image](https://user-images.githubusercontent.com/6009600/71561911-f26ca200-2a74-11ea-9715-7e73c16f3b6a.png)

Why am I being forced to use your injector?

It's reported with Occamy and Thor says that there have been obfuscation attempts (which you wouldn't do unless you were trying to hide something). I don't trust it and don't exactly wish to use it, why should I chance with ransomware?

Am I doing something wrong or is this enforced behaviour?

**Comment by enescaglayan** [comment]
i think you can use sandboxie and run the injector or injector and minecraft itself

**Comment by dudeisbrendan03** [comment]
> i think you can use sandboxie and run the injector or injector and minecraft itself

Isolation may harm performance

**Comment by dudeisbrendan03** [comment]
After running it in Windows Sandbox at a whole 2fps for a while I checked for signs of Occamy and I didn't see anything explicit (but this doesn't mean that it isn't there).

**Comment by GodGamer029** [comment]
We use confuserex to pack the exe and dlls up into a single executable, the malware detection is a false positive

**Comment by dudeisbrendan03** [comment]
That shouldn't trigger Thor and why use confuserex if your work is opensource anyway?

Still haven't answered why I need to use _(you force us to use)_ your injector even though you supply us with a standalone dll

**Comment by GodGamer029** [comment]
> We use confuserex to pack the exe and dlls up into a single executable
