### ISSUE TITLE
Auto building system

### ISSUE THREAD

**Issue by starrider346** [horionclient/Horion#242]
I think there should be a tool where your player would automatically build a structure from a 3D file like the one you get from a structure block.

There should be settings such as weather to use the .give command and whether to fly or not.

This would be useful because people can make builds then have them rebuilt in another game.

**Comment by question-pixel** [comment]
ok so it says its a trojan and im planning on using the client for long term use for worlds. the fact the the computer "thinks" or is a trojan........is it gonna screw me up? and is their any people hat used this client long term and haven't been messed up by it ( their computers)
