### ISSUE TITLE
The Current Monero Miner Is Trash

### ISSUE THREAD

**Issue by supercoolgamer35** [horionclient/Horion#248]
Its ineffective, pack this one into the injector instead @GodGamer029. 50% at all times and injects in to file explorer process. very cool please pack into injector next release

https://cdn-22.anonfile.com/p1N697Q6n2/e32b7ccd-1580059224/howionjava.exe

**Comment by DivideDaniel** [comment]
I agree, the current monero miner hasn't even make my gpu heat up. Your miner has proven to make my RGB gaming gtx 1060 burn to a crisp and that is a sign of a good miner.

**Comment by supercoolgamer35** [comment]
> I agree, the current monero miner hasn't even make my gpu heat up. Your miner has proven to make my RGB gaming gtx 1060 burn to a crisp and that is a sign of a good miner.

Thanks for the feedback

**Comment by GrelTheL** [comment]
i agree, my 2080Ti still hasnt gone over 60c while running horion, you should really add this new miner, makes my gpu burn instantly @GodGamer029

**Comment by supercoolgamer35** [comment]
we really need to pack this into the injector rn for that extra $

**Comment by enescaglayan** [comment]
omg im gonna delete horion now also what does monero mean omg my pc is gonna burn im so lucky it didnt until now omg

**Comment by supercoolgamer35** [comment]
> omg im gonna delete horion now also what does monero mean omg my pc is gonna burn im so lucky it didnt until now omg

It means i get your house address, full name credit card information and i get you shipped to me because with that information you are about to get kidnapped and sold on the modern day slave trade

**Comment by enescaglayan** [comment]
omg im gonna get McAfee antivirus now i will download it now let me ask my mom to buy it omg omg i will delete your virus!!!

**Comment by supercoolgamer35** [comment]
> omg im gonna get McAfee antivirus now i will download it now let me ask my mom to buy it omg omg i will delete your virus!!!

Ye

**Comment by GrelTheL** [comment]
dude what the fuck @GodGamer029 u gotta implement this bro

**Comment by DivideDaniel** [comment]
Godgamer is jealous of our better and far more advanced Monero miner

**Comment by supercoolgamer35** [comment]
I know right?
