### ISSUE TITLE
It gave me a shit ton of errors like wtf did i do wrong

### ISSUE THREAD

**Issue by RealEnzoTDZ** [horionclient/Horion#258]
The title and this picture explains all i use vs 2019 and c++ module

https://imgur.com/a/Cu08FXo

**Comment by baseds** [comment]
yep bro, explains it all, horion broken, you are best code install proper 😄 风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞风吹华南要塞

**Comment by RealEnzoTDZ** [comment]
no idea what the fuck i did

**Comment by RealEnzoTDZ** [comment]
the wiki is no help

**Comment by RealEnzoTDZ** [comment]
wow richard can you atleast try

**Comment by OrchaHax** [comment]
> wow richard can you atleast try

Easy fix
