### ISSUE TITLE
How to set build to public and not dev

### ISSUE THREAD

**Issue by RealEnzoTDZ** [horionclient/Horion#263]
**Describe the bug**
Only getting dev build

**To Reproduce**
1. Go to 'vs'
2. Click on 'build'
3. See error

**Expected behavior**
Only getting dev build

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
How would i get my build to be public or beta and not dev when i select betaconf or release it errors out

**Comment by richardletshacks** [comment]
https://docs.microsoft.com/en-us/visualstudio/mac/create-and-edit-configurations?view=vsmac-2019
