### ISSUE TITLE
horion commands (client) crashing the game

### ISSUE THREAD

**Issue by richardletshacks** [horionclient/Horion#269]
`addCommandToChatHistory` crashing the game, 1.16.40

**Comment by GodGamer029** [comment]
https://github.com/horionclient/Horion/blob/master/Memory/Hooks.cpp#L336 probably offsets changed

**Comment by bluedragon4418** [comment]
> https://github.com/horionclient/Horion/blob/master/Memory/Hooks.cpp#L336 probably offsets changed

Is there a way to fix it?
