### ISSUE TITLE
I don’t know why but on version 1.16.20 commands doesn’t work

### ISSUE THREAD

**Issue by my394** [horionclient/Horion#280]

**Comment by HAXORWAXOR** [comment]
What commands like because depending on the server some commands like .dupe or .give wont work

**Comment by my394** [comment]
All commands doesn’t work it shows like I’m type a message not command

**Comment by HAXORWAXOR** [comment]
> All commands doesn’t work it shows like I’m type a message not command

could you try use english

**Comment by my394** [comment]
Ok I will use a translator

**Comment by my394** [comment]
when I write a command (.help .give .tp, etc.), it writes to me as if I were writing a message to the chat, but the killaura cheats are enabled and the tracer works

**Comment by my394** [comment]
I can give screenshots
