### ISSUE TITLE
Crash when opening chest on 2b2tpe

### ISSUE THREAD

**Issue by ASOwnerYT** [horionclient/Horion#291]
**Describe the bug**
When I open any chest on the server _2b2tPE.org_, the game closes/crashes. Even when I don't have any modules enabled. It almost always crashes. I tested it on a survival world, and it only happens on the 2b2tPE server.

**Desktop (please complete the following information):**
 - OS: Windows 10 version 20H2

**Comment by GodGamer029** [comment]
Can you provide more info? Does this happen on other servers as well?

**Comment by GreenPlumTea** [comment]
ASOwnerYT, this is Maxxie's server, correct?

If it is, then that's just Maxxie's shit anticheat combined chunk data limits

**Comment by ASOwnerYT** [comment]
It's 2b2tpe.org, by Infinite Games Network
