### ISSUE TITLE
Issues after injecting

### ISSUE THREAD

**Issue by ThatJadon26** [horionclient/Horion#297]
**Describe the bug**
When you join your world or a server/realm, and inject it, a few seconds later it freezes and crashes.

**To Reproduce**
1. Join your world or server
2. Inject it
3. You will notice it freezes and crashes.

If you wait for a few seconds after joining the server/world and inject it, it will have a screen telling you to update it and I have tried downloading it 2 times.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 feature update 2004]

**Comment by GodGamer029** [comment]
minecraft version?

**Comment by HAXORWAXOR** [comment]
Try injecting it on the main menu and not in a world

**Comment by GreenPlumTea** [comment]
Downgrade to 1.14.2 and try.

**Comment by ThatJadon26** [comment]
I’m using 1.16.40 and I have tried injecting it on the menu and when I go on the game it still crashes.

**Comment by ThatJadon26** [comment]
My friend said it was because I need the beta version, is that correct?

**Comment by GreenPlumTea** [comment]
There isn't a beta version any longer. Could you attach a recording of this happening?

**Comment by ThatJadon26** [comment]
I can't upload a video.

**Comment by ItsYaBoyTac** [comment]
i crash too

**Comment by DrPleaseRespect** [comment]
Try to Build the DLL your self.

**Comment by Bedo05** [comment]
I have had this issue for a month now and am having the same problems as ThatJadon26.  I notice that If I open chat in a world my game will not crash intill I close chat and can move around.  Idk if that will help but I really could use a solution!   If u want me to provide anything to help u I will but I need help with this!

**Comment by GreenPlumTea** [comment]
First of all, I'd say downgrade to 1.16.20; It's just... more stable.

**Comment by ThatJadon26** [comment]
> First of all, I'd say downgrade to 1.16.20; It's just... more stable.

How tf would I downgrade and 2. I don't want to

**Comment by ThatJadon26** [comment]
Um so why is the issue closed?
