### ISSUE TITLE
Download site for injector wont load

### ISSUE THREAD

**Issue by freezebladeJD** [horionclient/Horion#301]
Whenever trying to load up https://www.horionbeta.club it says about blank then connection timed out. Please help.

**Comment by joswinjohn** [comment]
I'm having the same problem, I believe their website is down right now

**Comment by IceCruelStuff** [comment]
Im pretty sure they shutdown the website because this project is under no active development by the horion team

**Comment by FloppyDolphin57** [comment]
> I think they shutdown the website because this project is under no active development by the horion team

No it is just down right now. As they stated they will "Continue to host horion".

**Comment by IceCruelStuff** [comment]
> No it is just down right now. As they stated they will "Continue to host horion".

ok

**Comment by GodGamer029** [comment]
My bad, my server hosting provider shuts down the server sometimes because of too much traffic
