### ISSUE TITLE
Server command execution

### ISSUE THREAD

**Issue by DancingXXL** [horionclient/Horion#302]
**Is your feature request related to a problem? Please describe.**
I wanted to write a script that will execute server commands for some purpose, but it turned out to be impossible

**Describe the solution you'd like**
Horion command/scripting method to execute server command

**Comment by GodGamer029** [comment]
implemented

**Comment by DancingXXL** [comment]
@GodGamer029 I cannot find how to use this

**Comment by DancingXXL** [comment]
???
