### ISSUE TITLE
To many requests, please try again later.

### ISSUE THREAD

**Issue by freezebladeJD** [horionclient/Horion#304]
I'm getting an error message on download saying "To many requests, please try again later." Do i wait or is it something on my end? I've been waiting an half hour and still not working.

**Comment by GodGamer029** [comment]
yea you shouldn't download that often

**Comment by freezebladeJD** [comment]
> yea you shouldn't download that often

No i'd never downloaded before it was my first time but it's fixed now. Thanks anyway
