### ISSUE TITLE
Horion Commands

### ISSUE THREAD

**Issue by 3raden** [horionclient/Horion#305]
**Horion Commands Dont Work**
 I don't know whats going on but the horion commands arent working and I cannot find a fix,

**Comment by richardletshacks** [comment]
What exactly isnt working?

**Comment by FloppyDolphin57** [comment]
> What exactly isnt working?

I think he just changed his prefix lmao

**Comment by 3raden** [comment]
I just got horion back from reinstalling my pc, now all of a sudden its not working

**Comment by 3raden** [comment]
> What exactly isnt working?

So the horion commands like .nbt and .cbe arent working for me, just reset my entire pc, now its not working

**Comment by DickWartCream** [comment]
tf does nbt even do

**Comment by GreenPlumTea** [comment]
NBT gives you an item with NBT data matching whatever you have copied on your clipboard. This allows you to easily spawn in shulkers of gear, or beehives that spawn lit tnt.
