### ISSUE TITLE
https://horionbeta.club/ Is Down!

### ISSUE THREAD

**Issue by RealEnzoTDZ** [horionclient/Horion#306]
**Describe the bug**
The website https://horionbeta.club/injector is currently down.

**To Reproduce**
1. Go to 'https://horionbeta.club/'
2. See error

**Expected behavior**
You will get the error horionbeta.club took too long to respond.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: All
**Additional context**

**Comment by JibreelK** [comment]
Yup, same problem with me.

**Comment by brampedgex** [comment]
Not a github related issue.
