### ISSUE TITLE
Coordinates unlocker

### ISSUE THREAD

**Issue by Drakesdrs** [horionclient/Horion#313]
I would love if there was a 'coordinates show' on horion and a 'coordinates hide'

**Comment by FloppyDolphin57** [comment]
You can turn them on or off bruh

**Comment by Drakesdrs** [comment]
> You can turn them on or off bruh

on servers you cant

**Comment by HAXORWAXOR** [comment]
you can use the horion hud

**Comment by Drakesdrs** [comment]
> you can use the horion hud

WHERE IS HORION HUD

**Comment by GreenPlumTea** [comment]
double bruh

press insert
