### ISSUE TITLE
Token logger or bitcoin miner

### ISSUE THREAD

**Issue by 26926802306236** [horionclient/Horion#314]
I heard somewhere that Horion got turned into a token logger and bitcoin miner, are any of these true?

**Comment by riesters** [comment]
🤡

**Comment by 26926802306236** [comment]
bobux

**Comment by 26926802306236** [comment]
get epic nay nayed

**Comment by surfkitsune** [comment]
yeah it is to delete it you delete system 32 :)

**Comment by 26926802306236** [comment]
okay (promplty deletes system 54=

**Comment by 26926802306236** [comment]
and delets system 69

**Comment by surfkitsune** [comment]
no cap

**Comment by 26926802306236** [comment]
give me the bobux rn
