### ISSUE TITLE
Way to reset configs for Horion

### ISSUE THREAD

**Issue by 3raden** [horionclient/Horion#316]
I have just put the wrong prefix for horion and now I cannot rememeber what key I pressed, any way on how to reset horion configs or prefix?

**Comment by FloppyDolphin57** [comment]
press windows key + r paste this in and hit enter then delete the default.h file 
%Localappdata%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\RoamingState

**Comment by 3raden** [comment]
> press windows key + r paste this in and hit enter then delete the default.h file
> %Localappdata%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\RoamingState

Yes! Thank you
