### ISSUE TITLE
Apparently there is horion HUD 

### ISSUE THREAD

**Issue by Drakesdrs** [horionclient/Horion#318]
Where?

**Comment by riesters** [comment]
How fucking brain damaged can somebody be?

**Comment by Drakesdrs** [comment]
> How fucking brain damaged can somebody be?

Hello R1ester you are 38 why are you talking to me CREEP

**Comment by riesters** [comment]
> > How fucking brain damaged can somebody be?
> 
> Hello R1ester you are 38 why are you talking to me CREEP

Stop making retarded Issues

**Comment by brampedgex** [comment]
???????????????????
