### ISSUE TITLE
.dupe wont work

### ISSUE THREAD

**Issue by S1monuwu** [horionclient/Horion#320]
**Describe the bug**
When I do .dupe it just says "Duped 35 times" and moves the item to 3rd slot.

**To Reproduce**
1. .dupe
2. Error

**Expected behavior**
Dupe the item

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Cryptxy** [comment]
bro SHUT THE FUCK UUUUUUUUUUUP

**Comment by S1monuwu** [comment]
Fix it nerd
