### ISSUE TITLE
tpaura module code complete

### ISSUE THREAD

**Issue by aXxG3TR3KTxX591** [horionclient/Horion#321]
let module = Horion.getModuleManager().registerModule("TPAura");
let delay = 0;
let yOffset = 1;
let teleportDist = 4;
let maxRange = 7;

function onTick() {
	if (delay == 2) {
		if (Game.getLevel().isValid()) {
			let entTarget = getClosestEntity();
			if(entTarget !== undefined) {
				let xTarget = (entTarget.getPosition().x + randomFunction(Math.random() * teleportDist));
				let zTarget = (entTarget.getPosition().z + randomFunction(Math.random() * teleportDist));
				if(dist(Game.getLocalPlayer().getPosition(), entTarget.getPosition()) > maxRange) return;
				Game.getLocalPlayer().setPosition(Vec3(xTarget, entTarget.getPosition().y + 2 + yOffset, zTarget));
			}
			if(entTarget == undefined) return;
		}
		delay = 0;
	}
	delay++;
	Horion.getModuleManager().getModuleByName("Killaura").setEnabled(true);
}

function onDisable() {
	Horion.getModuleManager().getModuleByName("Killaura").setEnabled(false);
}

function getClosestEntity() {
    let lc = Game.getLocalPlayer();
    let entList = Game.getLevel().getAllTargetEntities();
	if(entList.length == 0) return undefined;
	let closestEnt = entList[0];
    entList.forEach(ent => {
        if(dist(lc.getPosition(), closestEnt.getPosition()) > dist(lc.getPosition(), ent.getPosition())) closestEnt = ent;
    });
	return closestEnt;
} 

function dist(pos1, pos2) {
    let sub = Vec3(pos1.x - pos2.x, pos1.y - pos2.y, pos1.z - pos2.z);
    let mag = Math.sqrt(sub.x * sub.x + sub.z * sub.z);
    return mag;
}

function randomFunction(num) {
	let testValue = Math.random();
	if (testValue < 0.5) return (-1 * num);
	return num;
}

module.registerCallback("onTick",onTick);
module.registerCallback("onDisable",onDisable);
module.registerCallback("onDisable",onDisable);

**Comment by aXxG3TR3KTxX591** [comment]
this is a c++ version of the tpaura script

**Comment by richardletshacks** [comment]
no?

**Comment by brampedgex** [comment]
first, thats javascript.
second, give me credit you monster!

**Comment by aXxG3TR3KTxX591** [comment]
> first, thats javascript.
> second, give me credit you monster!

i translated it to c++ so i put some work into it as well
