### ISSUE TITLE
(API) ChatHandler type for writing to in-game chat

### ISSUE THREAD

**Issue by Apollogeist** [horionclient/Horion#325]
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to write messages to the in-game chat, especially for streamlined debugging.

**Describe the solution you'd like**
Creation of a ChatHandler type that allows scripts to send messages in the chat.

**Describe alternatives you've considered**
I don't see any alternatives to implementing it that way.

**Additional context**
Yeah

**Comment by Hackerboi69420** [comment]
lmao im sure there is something like this already

**Comment by Apollogeist** [comment]
If there is it's not documented.

**Comment by GodGamer029** [comment]
there is log(), in dev mode it will print the messages to the chat
