### ISSUE TITLE
Minecraft Crash

### ISSUE THREAD

**Issue by ty246** [horionclient/Horion#327]
**Describe the bug**
I launched Minecraft 1.14.60, opened Horion Injector, pressed INJECT and Minecraft crashed.
If I don't press INJECT Minecraft just works.
How can I fix it?

![image](https://user-images.githubusercontent.com/61586104/96873587-d3188880-147d-11eb-82ae-9b359273308b.png)

![image](https://user-images.githubusercontent.com/61586104/96873609-d90e6980-147d-11eb-9996-418991c5170f.png)

**Comment by Flyable21** [comment]
same is happing with me

**Comment by ty246** [comment]
hole video link http://www.mediafire.com/file/x8oulzqw40afmad/2020-10-22+15-58-47.mkv/file

**Comment by GodGamer029** [comment]
downgrade to 1.16.40
