### ISSUE TITLE
(Scripting) DrawUtils support for 2D

### ISSUE THREAD

**Issue by Apollogeist** [horionclient/Horion#333]
**Is your feature request related to a problem? Please describe.**
DrawUtils is super convenient for a lot of things, but in my opinion support for 2D is a core feature.

**Describe the solution you'd like**
Functions for 2D shapes and lines, also text rendering.

**Describe alternatives you've considered**
These features could also be implemented separately from DrawUtils, though I think it would make more sense for them to be included.

**Comment by GodGamer029** [comment]
Done
