### ISSUE TITLE
not really a bug but...

### ISSUE THREAD

**Issue by ghostmantisboy** [horionclient/Horion#349]
How do i launch this application?

**Comment by JeffTried** [comment]
Omg. . .**freaking noobs** . . .  opening up a github issue just for that smh

**Comment by GodGamer029** [comment]
what

**Comment by ghostmantisboy** [comment]
i understand but i really cant figure it out.

**Comment by GodGamer029** [comment]
https://horionbeta.club

**Comment by ghostmantisboy** [comment]
thanks but it crashed minecraft when it injected into it

**Comment by ghostmantisboy** [comment]
do you have a solution?
