### ISSUE TITLE
re add godmode using a cbe explolit

### ISSUE THREAD

**Issue by aXxG3TR3KTxX591** [horionclient/Horion#355]
will auto give a particle bucket that gives effects resistance 255 for 1 sec and the particle follows you
all you need is to be able to spawn area effect cloud that gives effects and despawns almost instantly

**Comment by FloppyDolphin57** [comment]
Or just ka know give yourself creative mode?

**Comment by GreenPlumTea** [comment]
let CBE_GodmodeText = "Godmode-CBE";
let execute_CBEGodmode = "cbe effect @p[r=10] resistance 99999 255 true";
let module_qlzmt = Horion.getModuleManager().registerModule(CBE_GodmodeText);

function onEnable_qlzmt() {
	Horion.getModuleManager().getModuleByName(CBE_GodmodeText).setEnabled(false);
	Horion.getCommandManager().executeCommand(execute_CBEGodmode);
}

module_qlzmt.registerCallback("onEnable", onEnable_qlzmt);

This, pretty much? 
Taken and slightly edited from HorionRustMod and MCPELoanna0160's scripts.
