### ISSUE TITLE
artillery bow

### ISSUE THREAD

**Issue by aXxG3TR3KTxX591** [horionclient/Horion#360]
like bow aimbot but shoots directly into the air were the arrow will fly up in the air and will land like a artillery
useful if they are behind objects like a wall or to high to shoot up at

**Comment by GreenPlumTea** [comment]
Just use your other suggestion, bow trajectory for this? Like, this is really specific and weird.

**Comment by GreenPlumTea** [comment]
Or just add it to BowAimbot, I suppose. Why though?
