### ISSUE TITLE
nbt command crashs minecraft

### ISSUE THREAD

**Issue by aXxG3TR3KTxX591** [horionclient/Horion#370]
debug stack trace

Exception thrown at 0x00007FF926653E49 in Minecraft.Windows.exe: Microsoft C++ exception: std::invalid_argument at memory location 0x0000002CD97FC150.
Debug Assertion Failed!

Program: C:\Users\micha\Source\Repos\Horion\x64\Debug\Horion.dll
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\xstring
Line: 3637

Expression: front() called on empty string

on Line:3637 
_STL_VERIFY(_Mypair._Myval2._Mysize != 0, "front() called on empty string");

assets:
loaded dll SHCore.dll
executable name Minecraft.Windows.exe

**Comment by GreenPlumTea** [comment]
Video or replication method?
