### ISSUE TITLE
add check inventory to scripting 

### ISSUE THREAD

**Issue by aXxG3TR3KTxX591** [horionclient/Horion#373]
for example i want it to give me a item but i don't want it spamming it so i want it to check my inventory  to see if it has been used so after i have used a totem it will give me another cus it checked my inventory and there is none

**Comment by Mixu78** [comment]
I'm actually working on something like this rn

**Comment by aXxG3TR3KTxX591** [comment]
> I'm actually working on something like this rn

do you have a working test code
