### ISSUE TITLE
kill aura does not attack xp orbs and items

### ISSUE THREAD

**Issue by aXxG3TR3KTxX591** [horionclient/Horion#375]
kill aura ignores xp orbs and items

**Comment by CortexPE** [comment]
why would you want that?

PocketMine even kicks you for attacking an item.

**Comment by TheArmagan** [comment]
why you want that ?

**Comment by justinbrick** [comment]
i'm gonna have to ditto all the other comments, i can't see a single reason to add something like that.

**Comment by Apollogeist** [comment]
Do you mean you _don't_ want KA to attack XP orbs and items?
