### ISSUE TITLE
[Suggestion] Fake Player Check

### ISSUE THREAD

**Issue by Vonr** [horionclient/Horion#41]
Use information on the "Esc" menu to find player names then find matches with entities in auras/triggerbot so that you dont hit fake players.

**Comment by Damakermiddle** [comment]
- [ ] Get the info of all players.
- [ ] Link the information w/ kill aura, trigger and aimbot.
- [ ] Update the info simultaneously.

**Comment by Vonr** [comment]
needs to be asynchronous if you want both to happen at the same tick which im not sure if its possible

**Comment by Vonr** [comment]
but delay is fine i guess
