### ISSUE TITLE
[Suggestion] Improve Command Usage

### ISSUE THREAD

**Issue by QRSynq** [horionclient/Horion#70]
Be able to send multiple commands in one message. Ex. ".enchant 9 5 .enchant 17 3" To put sharpness and unbreaking on an item quickly.

**Comment by richardletshacks** [comment]
We could maybe add some bulk enchanting, however sending multiple commands in one message isn't possible.

**Comment by QRSynq** [comment]
I would only use that feature for enchanting anyways, thanks for responding!
