### ISSUE TITLE
Bhop disables normal jumping/bhop spamming with airjump on

### ISSUE THREAD

**Issue by bgamboe** [horionclient/Horion#76]
When bhop is activated you cannot use the normal jump button.
When bhop is activated you will jump infinitely and quite rapidly into the air when airjump is enabled.

**Comment by richardletshacks** [comment]
Why would you use the normal jump button when you already use bhop?

**Comment by richardletshacks** [comment]
This was fixed in [this commit](https://github.com/horionclient/Horion/commit/169ceced9e67a9cbba99e8d35c31d065d0b5a725)
