### ISSUE TITLE
NoFall Bug

### ISSUE THREAD

**Issue by PeanutGriffin** [horionclient/Horion#83]
NoFall disturbs the mid-air deployment of elytra randomly and also disables using fireworks to launch off with an elytra,

**Comment by Greloom-Yeet** [comment]
NoFall sets the fallDistance to 0. The Elytra requires you to be in mid air however setting the fallDistance to 0 makes MC think you're just on ground. Probably can't be fixed.
Just turn off NoFall when using Elytra

**Comment by d1gress** [comment]
set falldistance to 0.5

**Comment by SurvirvorHRG** [comment]
fixed
