### ISSUE TITLE
Cannot go under 2 or 3 block high space.

### ISSUE THREAD

**Issue by infrustrationMC** [horionclient/Horion#89]
I seems to cannot do that even with only Fullbright and TabGui on

**Comment by richardletshacks** [comment]
Could you provide further what you did?

**Comment by infrustrationMC** [comment]
So on a realm, when i want to go under a space that blocks are right or 1 block above my head, it seems like I'm going against an invisible wall. This sometimes happen.

**Comment by richardletshacks** [comment]
Do you know if there was an invisible barrier block?

**Comment by infrustrationMC** [comment]
No, pure generated terrain

**Comment by richardletshacks** [comment]
Were you able to go under that space when Horion wasn't injected?

**Comment by infrustrationMC** [comment]
https://youtu.be/VPQMbMotMv8

Also turns out there are blocks there on server side, and the event haven't been registered from the client yet.

But what weird is when I go into the nether portal, it wont allow me cause the height is less than 4 blocks. Also for natural generated tree for example oak tree, there are nothing there on server-side and it still wont allow me to go through.

After recording the clip, I eject the client but still can go through, I relog and the blocks now apper on client-side

**Comment by Zelqx** [comment]
That happens because you entered freecam, after you entered freecam, go and phase into the invis client sided blocks and it should fix the problem, i do this everytime.
