### ISSUE TITLE
a weird clickgui bug

### ISSUE THREAD

**Issue by Armagann** [horionclient/Horion#91]
**i can't close and click the gui**
---

Click image to play gif
[![a weird bug](https://i.imgur.com/oSf3aGi.png)](https://i.imgur.com/IvHi7N9.gif)

**Comment by richardletshacks** [comment]
How about you just collect the issues and post them as whole?

Anyways, what did you do before this happened?

**Comment by Armagann** [comment]
.toggle clickgui

**Comment by SurvirvorHRG** [comment]
Just press escape

**Comment by Armagann** [comment]
@SurvirvorHRG i can't press any key..
