### ISSUE TITLE
Killaura bug

### ISSUE THREAD

**Issue by Zelqx** [horionclient/Horion#92]
Killaura wont kill swimming players and flying players ( elytra users ) basicly anyone's hit box that changed to a small hitbox

**Comment by richardletshacks** [comment]
Can you provide more details?

**Comment by Zelqx** [comment]
So you know when players' hitboxes go smaller when they swim/fly with the elytra? Killaura ignores them and only goes for normal size hitboxes

**Comment by richardletshacks** [comment]
kinda fixed
