### ISSUE TITLE
version 2.0.0 and daily builds fly puts you in pseudo creative

### ISSUE THREAD

**Issue by gr4ndmux** [horionclient/Horion#94]
LOVE LOVE LOVE that give works now!!!

Love a ton of things, some of these seem too cool!

I didn't know it was a build issue until digging into it.

Please confirm if you guys reading experince it too.
But 
No Fall, Infinite Reach, Full Bright, Fast East, Tab Gui + Fly

WILL ALWAYS put you in a creative mode loop, you cant override out of it, and its always tied to the fly module. 

Please revert fly or give advice on how to get it to work with all these other new modules.

**Comment by gr4ndmux** [comment]
Here is a quick video with proof - https://youtu.be/dZTfJjzPXOs

**Comment by gr4ndmux** [comment]
the latest nightly #20191014.3 "fixed" being able to pull up inventory with E and changing out the hot bar, this is plenty good for me to call it fixed, but the healthbar and hotbar need similar patching too.

**Comment by Greloom-Yeet** [comment]
Known issue.

**Comment by Greloom-Yeet** [comment]
Getting fixed in a second.

**Comment by Zelqx** [comment]
Second = 10 days or more
