### ISSUE TITLE
.give bug

### ISSUE THREAD

**Issue by joem23** [horionclient/Horion#97]
Game crashes when entering an item's namespace id that isn't valid.

Example: .give eye_of_ender 1 crashes game since eye_of_ender isn't the valid ID.

.give ender_eye 1, however, does not crash.

**Comment by richardletshacks** [comment]
This is known and will be fixed later.

**Comment by d1gress** [comment]
get the fix from https://github.com/Greloom-Yeet/Horion/blob/master/Horion/Command/Commands/GiveCommand.cpp
